name: Github Personal Website
run-name: ${{ github.actor }}
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: After build project
        run: |
          rm -rf README.md node_modules index.html package.json package-lock.json public src tailwind.config.js vite.config.js yarn.lock .github
          mv -f dist/* .
          rm -rf dist
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git stash --include-untracked
          git fetch origin
          if git ls-remote --exit-code --heads origin gh-pages; then
            git checkout origin gh-pages
            git add .
            git commit -m "Deploy to GitHub Pages Sudah Ada"
            git push -u origin gh-pages
            git checkout -
            git stash pop
          else
            git checkout --orphan gh-pages
            rm -rf README.md node_modules index.html package.json package-lock.json public src tailwind.config.js vite.config.js yarn.lock .github
            mv -f dist/* .
            rm -rf dist
            git add .
            git commit -m "Deploy to GitHub Pages Baru"
            git push -u origin gh-pages
            git checkout -
            git stash pop
          fi